[package]
name = "rlox-intermediate"
version = "0.1.0"
edition = "2021"

[dependencies]
codespan-reporting = "0.11.1"
paste = "1.0.15"
phf = { version = "0.11.2", features = ["macros"] }

[features]
disassembler = []
gc-sanitizer = []