[package]
name = "rlox-intermediate"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
codespan-reporting = "0.11.1"
phf = { version = "0.11.2", features = ["macros"] }
