[package]
name = "rlox-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
rlox-intermediate = { path = "../rlox-intermediate" }
smallvec = { version = "1.13.2", features = ["const_generics"] }

[features]
stack-monitor = []
gc-sanitizer = []
